AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: thankshell platform

Parameters:
  CfnBucketName:
    Type: String
  GroupMembersTableName:
    Type: String

Resources:
  ###############################################
  # Storage

  CfnBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref CfnBucketName

  ###############################################
  # Database

  GroupMembersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref GroupMembersTableName
      BillingMode: PAY_PER_REQUEST
      KeySchema:
      - KeyType: HASH
        AttributeName: group_id
      - KeyType: RANGE
        AttributeName: member_id
      AttributeDefinitions:
      - AttributeName: group_id
        AttributeType: S
      - AttributeName: member_id
        AttributeType: S
